### ISSUE TITLE
Ignores collection properties with initializers

### ISSUE THREAD

**Issue by geirsagberg** [CodySchrank/MTT#30]
Given the classes:

```
public class ItemModel {
  public string Title { get; set; }
}

public class MyListModel {
  public string Title { get; set; }
  public ICollection<ItemModel> Items { get; set; } = new List<ItemModel();
}
```

The generated file for `MyListModel` is:

```
export interface MyListModel {
  title: string;
}
```

If I remove the collection initializer, i.e.:
```
public class MyListModel {
  public string Title { get; set; }
  public ICollection<ItemModel> Items { get; set; }
}
```

Then it generates correctly:
```
import { ItemModel } from "./itemModel"

export interface MyListModel {
  title: string;
  items: ItemModel[];
}
```

Also, I noticed `IList`-properties are generated as `any` instead of arrays.

**Comment by CodySchrank** [comment]
Thanks for the PR!  Generally DTO's are not initialized like a traditional class which is why I never coded it in, but if you want it for your use case I have no problem adding it in as long as it doesn't affect anything else.  I'll review it soon, and I see you already wrote a test for it I appreciate that :)
