### ISSUE TITLE
Nullable types with ?

### ISSUE THREAD

**Issue by rcheung9** [CodySchrank/MTT#34]
If I have a property such as `public bool? IsCurrent { get; set; }`, it gets converted to `isCurrent?: boolean;`

It should be `isCurrent: boolean | null;`

**Comment by CodySchrank** [comment]
The converted ts is technically equivalent to `isCurrent: boolean | undefined;`, because it is an optional prop so it doesn't have to have a value, ie. it defaults to undefined.  So this is really a discussion of null vs undefined.  

For what this tool is trying to accomplish I think that is fine.  Either the value is going to exist or it isn't, which is what a ts optional is for.  And the general consensus in the community is to use undefined over null when given the option.

Here's some reference as to why I chose this:
https://stackoverflow.com/questions/44536340/typescript-what-is-the-difference-between-null-and-undefined

https://stackoverflow.com/questions/49746803/typescript-null-versus-undefined
